language: c
compiler:
  - gcc

before_script:
  - NGINX_VERSION=1.5.8
  - CIRON_VERSION=1.2
  - HAWKC_VERSION=0.8.2
  - export IRON_PASSWORD_1=982349872349234293429347923492837
  - export IRON_PASSWORD_2=110199373028353707875890923487628
  - cd ../
  - curl -LO http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
  - tar -xzf nginx-${NGINX_VERSION}.tar.gz
  - rm nginx-${NGINX_VERSION}.tar.gz
  - curl -LO https://github.com/algermissen/ciron/archive/v${CIRON_VERSION}.zip
  - unzip v${CIRON_VERSION}.zip
  - rm v${CIRON_VERSION}.zip
  - curl -LO https://github.com/algermissen/hawkc/archive/v${HAWKC_VERSION}.zip
  - unzip v${HAWKC_VERSION}.zip
  - rm v${HAWKC_VERSION}.zip
  - cd ciron-${CIRON_VERSION}
  - ./configure && make all && make test
  - sudo make install
  - cd ..
  - cd hawkc-${HAWKC_VERSION}
  - ./configure && make all && make test
  - sudo make install
  - cd ..
  - find .
  - cd nginx-${NGINX_VERSION}
  - ./configure --add-module=../nginx-dlg-auth
  - make && sudo make install
  - cd ..
  - cat nginx-dlg-auth/test/nginx.conf | m4 -DIRON_PASSWORD_1=$IRON_PASSWORD_1 -DIRON_PASSWORD_2=$IRON_PASSWORD_2 > tmp
  - sudo cp tmp /usr/local/nginx/conf/nginx.conf
  - rm tmp
  - cat /usr/local/nginx/conf/nginx.conf
  - sudo /usr/local/nginx/sbin/nginx
  - chmod a+x nginx-dlg-auth/test/run_tests.sh
  - chmod a+x nginx-dlg-auth/test/test*

script: cd nginx-dlg-auth/test; ./run_tests.sh


after_script:
  - cat /usr/local/nginx/logs/access.log
  - cat /usr/local/nginx/logs/error.log

