language: c
compiler:
  - gcc

before_script:
  - NGINX_VERSION=1.5.8
  - CIRON_VERSION=1.0
  - HAWKC_VERSION=0.7
  - cd ../
  - curl -LO http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
  - tar -xzf nginx-${NGINX_VERSION}.tar.gz
  - rm nginx-${NGINX_VERSION}.tar.gz
  - curl -LO https://github.com/algermissen/ciron/archive/v${CIRON_VERSION}.zip
  - unzip v${CIRON_VERSION}.zip
  - rm v${CIRON_VERSION}.zip
  - curl -LO https://github.com/algermissen/hawkc/archive/v${HAWKC_VERSION}.zip
  - unzip v${HAWKC_VERSION}.zip
  - rm v${HAWKC_VERSION}.zip
  - cd ciron-${CIRON_VERSION}
  - ./configure && make all && make test
  - make install
  - cd ..
  - cd hawkc-${HAWKC_VERSION}
  - ./configure && make all && make test
  - make install
  - cd ..
  - find .
  - ls /usr/local/include
  - ls /usr/local/lib
  - cd nginx-${NGINX_VERSION}
  - ls
  - ./configure --add-module=../nginx-dlg-auth
  - make && make install
  - cat /usr/local/nginx/conf/nginx.conf


